<a href="https://colab.research.google.com/github/N1tingale/PyTorch/blob/main/PyTorch_Fundamentals_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Introduction to Tensors
### Scalar

In [ ]:
# Scalar
# Usually the variable name is lowercase in code
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get number of tensor dimensions
scalar.ndim

0

In [ ]:
# Get python equivalent of the tensor
scalar.item()

7

In [ ]:
# Vector
# Usually the variable name is lowercase in code
vector = torch.tensor([[1],[2],[3]])
vector

tensor([[1],
        [2],
        [3]])

In [ ]:
# Get shape of the tensor
vector.shape

torch.Size([3, 1])

In [ ]:
# MATRIX
# Usually the variable name is uppercase in code
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
# Usually the variable name is uppercase in code
TENSOR = torch.tensor([[[1,2,3]]])

### Random Tensors

Random tensors are important, because many neural networks learn by starting with tensors with random numbers, and then adjusting them to better represent the data.

One example of such a workflow would be:
1. Start with random numbers
2. Look at the data
3. Update the random numbers
4. Repeat steps 2-3

In [ ]:
# Create a random tensor of size/shape (a, b)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8627, 0.3491, 0.7911, 0.4286],
        [0.4462, 0.6737, 0.4673, 0.4292],
        [0.6946, 0.0960, 0.4114, 0.1815]])

In [ ]:
# Create a random tensor with a shape similar to an image tensor
random_image_shape_tensor = torch.rand(size = (224,223,3))
random_image_shape_tensor.shape, random_image_shape_tensor.ndim

(torch.Size([224, 223, 3]), 3)

### A tensor of zeros and ones

In [ ]:
# Create a tensor of zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors shaped like other tensors

In [ ]:
# Use torch.arange() - torch.range() is deprecated!
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range_zeroes = torch.zeros_like(input=range)
range_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Another example:
rand_vector = torch.rand((2,4))
rand_vector_zeroes = torch.zeros_like(input=rand_vector)
rand_vector, rand_vector_zeroes

(tensor([[0.9944, 0.2862, 0.4736, 0.8911],
         [0.6585, 0.5049, 0.0777, 0.4047]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### Tensors datatypes

Note: Tensor datatypes is one of the three main issues that are often enountered in PyTorch and Deep Learning:
1. Wrong datatype of a tensor
2. Wrong shape of a tensor
3. A tensor is on a wrong device

In [ ]:
# Float 32 tensor
# Parameters dtype, device and requires_grad are the 3 most important parameters when creating tensor

# dtype is the datatype of the tensor (e.g float32, float 16 etc.)

# device is the hardware which is used to creat the tensor - it is set to cpu by default but can be changed
# One error we may get is when trying to do operations on tensors that are on different devices and are therefore incompatible

# required_grad is for when we want to track the gradience of a tensor when it through certain calculations

float_32_tensor = torch.tensor([1.5,2.5,4.5], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1.5000, 2.5000, 4.5000])

In [ ]:
# Even thought the dtype is specified as none, it will still default to float32
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([2.0, 4.0, 6.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
# One way to convert a tensor from one dtype to another would be to use the .type() method:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Tensor attributes (getting information about tensors)

In [ ]:
tensor_product = float_16_tensor * float_32_tensor
tensor_product

tensor([ 2.2500,  6.2500, 20.2500])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor.dtype

torch.int32

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 4.5000, 15.0000, 40.5000])

### Getting information from tensors:
1. shape - `tensor.shape`
2. datatype - `tensor.dtype`
3. device - `tensor.device`

In [ ]:
# Find out details about a sample tensor:
tensor = torch.rand(size=(3,4,5))
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor datatype: {tensor.dtype}")
print(f"Tensor device: {tensor.device}")

Tensor shape: torch.Size([3, 4, 5])
Tensor datatype: torch.float32
Tensor device: cpu


### Changing tensor attributes
To change dtype or device for a tensor, we can use the `.to()` method

In [ ]:
# Change tensor from float32 to float16
float32_tensor = torch.rand(size=(3,4), dtype=torch.float32)
print(float32_tensor.dtype)
float16_tensor = float32_tensor.to(dtype=torch.float16)
print(float16_tensor.dtype)

torch.float32
torch.float16


### Tensor operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Matrix multiplication (dot product)
* Division


In [23]:
# Addition
tensor = torch.tensor([4,5,6])
tensor + 10

tensor([14, 15, 16])

In [24]:
tensor1 = torch.tensor([6,7,8])
tensor + tensor1

tensor([10, 12, 14])

In [25]:
# Scalar multiplication
tensor * 10

tensor([40, 50, 60])

In [26]:
# Subtraction
tensor - 20

tensor([-16, -15, -14])

In [27]:
# Division
tensor / 10

tensor([0.4000, 0.5000, 0.6000])

In [28]:
# Element wise mulitplication
tensor1 = torch.tensor([2,3,4])
tensor2 = torch.tensor([6,7,8])
tensor1 * tensor2

tensor([12, 21, 32])

In [29]:
# Matrix multiplication
torch.matmul(tensor1, tensor2)

tensor(65)

### A common issue in deep learning is shape errors:
Having tensors of incorrect size when trying to do matrix multiplication results in an error

There are two main rules that should be follwed when performing matrix operations:
1. The **inner dimensions** must match:
* `(3,2) @ (2,3)` will work, but
* `(3,2) @ (3,2)` won't work
2. The resulting matrix must have the shape of the **outer dimensions**:
* `(3,2) @ (2,3)` will have shape (3,3)
* `(4,5) @ (5,4)` will have shape (5,5)

In [ ]:
# Shapes for matrix multiplication
tensor1 = torch.tensor([[1,2], [3,4], [5,6]])
tensor2 = torch.tensor([[7,8,9], [10,11,12]])
torch.matmul(tensor1, tensor2)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### To fix shape mismatch issue when multiplying tensors, we can use transpose:

**Transpose** switched the rows and columns of a tensor

It lets us turn a tensor of shape (a,b) into tensor of shape (b,a)


In [ ]:
# Example:
tensor1 = torch.tensor([[1,2], [3,4], [5,6]])
tensor2 = torch.tensor([[7,8], [10,11], [12,13]])
torch.mm(tensor1, tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Since the last case resulted in an error, we can now transpose one of the tensors to be able to use matrix multiplication on them:
tensor2 = tensor2.T
torch.mm(tensor1, tensor2)

tensor([[ 23,  32,  38],
        [ 53,  74,  88],
        [ 83, 116, 138]])

### Tensor aggregation
There are other operation we may do on tensors that give us some information about their contents:
* min
* max
* mean
* sum

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# .min() - returns the smallest element of the tensor
x.min()

tensor(0)

In [ ]:
# .min() - returns the largest element of the tensor
x.max()

tensor(9)

In [ ]:
# .sum() returns the sum of the elements of the tensor
x.sum()

tensor(45)

In [ ]:
# .mean() returns the mean of the elements of the tensor
# !!! Only works with complex or float types
x = x.to(dtype=torch.float32)
x.mean()

tensor(4.5000)

In [ ]:
# To find the position of the min and max values, we can use torch.argmin() and torch.argmax():
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping is the operation of reshaping a tensor into a different shape
* View returns a view of an input tensor of certain shape, but keeps the same memory as original tensor
* Stacking is the operation of combining multiple tensors
  * vstack - vertical stack, stacks tensors vertically
  * hstack - horizontal stack, stacks tensors side by side
* Squeezing is the operation of removing all `1` dimensions from a tensor
* Unsqueezing is the operation of adding a `1` dimension to a tensor
* Permuting returns a view of the input with certain dimensions swapped

In [1]:
# Reshape - change dimensions of a tensor by adding an extra one
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# Reshape
# Add an extra dimension (the reshape shape must be compatible with the dimension of the original)
# For the reshape to work, the multiple of the new dimensions must be the same as the multiple of the previous dimensions
x.reshape(shape=(1,9))


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [3]:
x.reshape(shape=(9,1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [4]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [5]:
# View
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
z.shape

torch.Size([1, 9])

In [7]:
# The view is similar to reshape, but shares the memory with the original tensor
# Changing z will now also change x:
z *= 10
z, x

(tensor([[10., 20., 30., 40., 50., 60., 70., 80., 90.]]),
 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [8]:
# Stack - stack an extra tensor on top or side by side of another one
torch.stack([x,x], dim=0)

tensor([[10., 20., 30., 40., 50., 60., 70., 80., 90.],
        [10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [9]:
torch.stack([x,x], dim=1)

tensor([[10., 10.],
        [20., 20.],
        [30., 30.],
        [40., 40.],
        [50., 50.],
        [60., 60.],
        [70., 70.],
        [80., 80.],
        [90., 90.]])

In [10]:
# Squeeze - remove all 1 dimensions from a tensor
squeezed_tensor = torch.squeeze(torch.rand(size=(3,5,1,6,1)))
squeezed_tensor.shape

torch.Size([3, 5, 6])

In [11]:
# Unsqueeze - add a 1 dimension to a tensor
tensor = torch.tensor([1,2,3,4])
torch.unsqueeze(tensor, 0)

tensor([[1, 2, 3, 4]])

In [12]:
torch.unsqueeze(tensor, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [13]:
# Unsqueeze example:
tensor = torch.arange(1,11)
tensor_unsqueezed = tensor.unsqueeze(dim=0)
tensor, tensor.shape, tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([1, 10]))

In [14]:
# Squeeze example:
tensor_squeezed = tensor_unsqueezed.squeeze()
tensor_squeezed, tensor_squeezed.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [15]:
# Permute - rearrange the dimensions of a tensor in a specified order
x = torch.zeros(2,3,5)
x, x.shape

(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 torch.Size([2, 3, 5]))

In [16]:
x = x.permute(dims=(2,0,1))
x, x.shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]]]),
 torch.Size([5, 2, 3]))

In [18]:
# Another permute example - image tensor
image_tensor = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axes/dimensions order:
image_tensor_permuted = image_tensor.permute(dims=(2, 0, 1))
image_tensor_permuted, image_tensor_permuted.shape

(tensor([[[0.5103, 0.5325, 0.2954,  ..., 0.1780, 0.1023, 0.7391],
          [0.7388, 0.0359, 0.0253,  ..., 0.6767, 0.4128, 0.3484],
          [0.4625, 0.3951, 0.7489,  ..., 0.9712, 0.9617, 0.3353],
          ...,
          [0.3705, 0.3352, 0.0578,  ..., 0.2874, 0.8242, 0.4974],
          [0.5617, 0.9035, 0.8165,  ..., 0.5294, 0.2906, 0.4864],
          [0.0285, 0.9714, 0.2481,  ..., 0.0304, 0.5564, 0.1678]],
 
         [[0.4287, 0.9152, 0.0633,  ..., 0.1456, 0.8652, 0.2198],
          [0.8163, 0.2178, 0.6330,  ..., 0.8171, 0.4363, 0.7330],
          [0.3304, 0.0759, 0.9741,  ..., 0.5576, 0.7380, 0.2340],
          ...,
          [0.6730, 0.3779, 0.8748,  ..., 0.8473, 0.1545, 0.4710],
          [0.4287, 0.8068, 0.7437,  ..., 0.2733, 0.3177, 0.9404],
          [0.8926, 0.3102, 0.2102,  ..., 0.7879, 0.8315, 0.6968]],
 
         [[0.3977, 0.5138, 0.6398,  ..., 0.0498, 0.3992, 0.6272],
          [0.9621, 0.2925, 0.1882,  ..., 0.4360, 0.4034, 0.2967],
          [0.3019, 0.9937, 0.5990,  ...,

### Selecting data from tensors (indexing)

Indexing with PyTorch is similar to indexing with NumPy

In [20]:
# Create a tensor
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
# Indexing the tensor:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
# Indexing the tensor on the middle bracket:
tensor[0][0]

tensor([1, 2, 3])

In [23]:
# Indexing the tensor on the innermost bracket:
tensor[0][0][0]

tensor(1)

In [24]:
# We can also use ":" to select a range from target dimension
tensor[:, 0]

tensor([[1, 2, 3]])

In [25]:
# Get all values of the 0 dimensions but only 1 index value of the first and second dimension
tensor[:,1,1]

tensor([5])

In [26]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensions
tensor[0,0,:]

tensor([1, 2, 3])

In [27]:
tensor[0][2][2]

tensor(9)

In [31]:
tensor[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch and Numpy

NumPy is a popular scientific python library

Because of this, PyTorch has functionality to interact with numpy

* Convert data from a NumPy array into a PyTorch tensor: `torch.from_numpy(ndarray) -> tensor`
* Convert a PyTorch tensor into a NumPy array: `torch.Tensor.numpy()`

In [32]:
import torch
import numpy as np

In [35]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting a numpy array to pytorch tensor, the tensor keeps the dtype of the array (float64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [36]:
array.dtype

dtype('float64')

In [37]:
tensor.dtype

torch.float64

In [38]:
tensor = torch.arange(1, 10)
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

### Reproducibility

Reproducibility in PyTorch is the process of trying to make the training and data more deterministic and reproducable to facilitate testing.

To reduce the randomness in neural networks and PyTorch we use the concept of a **random seed**.

Essentially what a random seed does is "flavour" the randomness.

In [1]:
import torch

# Create two random tensors
random_tensor1 = torch.rand(3,4)
random_tensor2 = torch.rand(3,4)
random_tensor1, random_tensor2, random_tensor1 == random_tensor2

(tensor([[0.6203, 0.3917, 0.2995, 0.9805],
         [0.3430, 0.5262, 0.6381, 0.0989],
         [0.4165, 0.2543, 0.8679, 0.5705]]),
 tensor([[0.8646, 0.2623, 0.2244, 0.5670],
         [0.8804, 0.2136, 0.3124, 0.1371],
         [0.0144, 0.6930, 0.6506, 0.5186]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [46]:
# Let's make some random but reproducibile tensors

# Set the random seed:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor4 = torch.rand(3,4)
random_tensor3, random_tensor4, random_tensor3 == random_tensor4

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Running tensors and PyTorch objects on GPUs (and making faster computations)
* GPUs can do tensor operations faster than a cpu can, thanks to CUDA and NVIDIA hardware + PyTorch working behind the scenes


In [2]:
!nvidia-smi

Wed Jan 10 18:21:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
# Check for GPU Access with PyTorch
torch.cuda.is_available()

True

In [6]:
# Setup device independent code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# Count the number of GPUs
torch.cuda.device_count()

1

### Putting tensors and models on the GPU



In [10]:
# Create a tensor (on CPU by default)
tensor = torch.tensor([1,2,3], device="cpu")

# Tensor on CPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [11]:
# Create a tensor on a GPU
gpu_tensor = torch.tensor([4,5,6], device='cuda')

# Tensor on GPU
gpu_tensor, gpu_tensor.device

(tensor([4, 5, 6], device='cuda:0'), device(type='cuda', index=0))

In [12]:
# We can also move the tensor from the CPU to the GPU if available:
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [14]:
# Sometimes, we need a tensor to be on a CPU instead of a GPU
# For example, NumPy only works with tensors that are on the CPU
tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
# To move a tensor back to the CPU we can use Tensor.cpu() method:
tensor_to_cpu = tensor_to_gpu.cpu()
tensor_to_cpu, tensor_to_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [18]:
tensor_to_cpu.numpy()

array([1, 2, 3])

### Exercises

In [33]:
# Create a random tensor with shape (7, 7).
tensor = torch.rand(7,7)
tensor

tensor([[0.8848, 0.1112, 0.4012, 0.1062, 0.5553, 0.3071, 0.8476],
        [0.8003, 0.1823, 0.6490, 0.1355, 0.6763, 0.2381, 0.6526],
        [0.1945, 0.5025, 0.2746, 0.7695, 0.4910, 0.2725, 0.0578],
        [0.0217, 0.6040, 0.6641, 0.5309, 0.9906, 0.6133, 0.4428],
        [0.5541, 0.9437, 0.8203, 0.1192, 0.9395, 0.7898, 0.7779],
        [0.4793, 0.9084, 0.7213, 0.7064, 0.9480, 0.4965, 0.2055],
        [0.5867, 0.9586, 0.3722, 0.9080, 0.7027, 0.8269, 0.5643]])

In [35]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
tensor1 = torch.rand(1,7)
tensor1 = tensor1.T

tensor_product = torch.matmul(tensor, tensor1)
tensor_product

tensor([[1.0782],
        [1.2263],
        [0.7660],
        [1.2835],
        [1.7877],
        [1.5383],
        [1.4615]])

In [58]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [59]:
tensor1 = torch.rand(1,7)
tensor1 = tensor1.T

tensor_product = torch.matmul(tensor, tensor1)
tensor_product

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [45]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [46]:
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
torch.manual_seed(1234)
tensor2 = torch.rand(2,3)

In [50]:
tensor1 = tensor1.to('cuda')
tensor2 = tensor2.to('cuda')
tensor1.device, tensor2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [51]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
tensor2 = tensor2.T
product = torch.matmul(tensor1, tensor2)
product

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [52]:
# Find the maximum and minimum values of the output of 7.
product.min(), product.max()

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [53]:
# Find the maximum and minimum index values of the output of 7.
product.argmin(), product.argmax()

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

In [56]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
tensor

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [57]:
new_tensor = tensor.squeeze()
new_tensor, new_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))