In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Introduction to Tensors
### Scalar

In [2]:
# Scalar
# Usually the variable name is lowercase in code
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get number of tensor dimensions
scalar.ndim

0

In [4]:
# Get python equivalent of the tensor
scalar.item()

7

In [5]:
# Vector
# Usually the variable name is lowercase in code
vector = torch.tensor([[1],[2],[3]])
vector

tensor([[1],
        [2],
        [3]])

In [6]:
# Get shape of the tensor
vector.shape

torch.Size([3, 1])

In [7]:
# MATRIX
# Usually the variable name is uppercase in code
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR
# Usually the variable name is uppercase in code
TENSOR = torch.tensor([[[1,2,3]]])

### Random Tensors

Random tensors are important, because many neural networks learn by starting with tensors with random numbers, and then adjusting them to better represent the data.

One example of such a workflow would be:
1. Start with random numbers
2. Look at the data
3. Update the random numbers
4. Repeat steps 2-3

In [11]:
# Create a random tensor of size/shape (a, b)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3894, 0.2124, 0.0039, 0.1950],
        [0.8947, 0.4703, 0.5093, 0.5216],
        [0.9783, 0.6997, 0.6438, 0.1982]])

In [12]:
# Create a random tensor with a shape similar to an image tensor
random_image_shape_tensor = torch.rand(size = (224,223,3))
random_image_shape_tensor.shape, random_image_shape_tensor.ndim

(torch.Size([224, 223, 3]), 3)

### A tensor of zeros and ones

In [13]:
# Create a tensor of zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
# Create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors shaped like other tensors

In [16]:
# Use torch.arange() - torch.range() is deprecated!
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
range_zeroes = torch.zeros_like(input=range)
range_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Another example:
rand_vector = torch.rand((2,4))
rand_vector_zeroes = torch.zeros_like(input=rand_vector)
rand_vector, rand_vector_zeroes

(tensor([[0.5106, 0.5840, 0.0247, 0.7063],
         [0.3337, 0.5822, 0.2877, 0.4822]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### Tensors datatypes

Note: Tensor datatypes is one of the three main issues that are often enountered in PyTorch and Deep Learning:
1. Wrong datatype of a tensor
2. Wrong shape of a tensor
3. A tensor is on a wrong device

In [20]:
# Float 32 tensor
# Parameters dtype, device and requires_grad are the 3 most important parameters when creating tensor

# dtype is the datatype of the tensor (e.g float32, float 16 etc.)

# device is the hardware which is used to creat the tensor - it is set to cpu by default but can be changed
# One error we may get is when trying to do operations on tensors that are on different devices and are therefore incompatible

# required_grad is for when we want to track the gradience of a tensor when it through certain calculations

float_32_tensor = torch.tensor([1.5,2.5,4.5], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([1.5000, 2.5000, 4.5000])

In [21]:
# Even thought the dtype is specified as none, it will still default to float32
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = torch.tensor([2.0, 4.0, 6.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [23]:
# One way to convert a tensor from one dtype to another would be to use the .type() method:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### Tensor attributes (getting information about tensors)

In [24]:
tensor_product = float_16_tensor * float_32_tensor
tensor_product

tensor([ 2.2500,  6.2500, 20.2500])

In [25]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor.dtype

torch.int32

In [27]:
int_32_tensor * float_32_tensor

tensor([ 4.5000, 15.0000, 40.5000])

### Getting information from tensors:
1. shape - `tensor.shape`
2. datatype - `tensor.dtype`
3. device - `tensor.device`

In [30]:
# Find out details about a sample tensor:
tensor = torch.rand(size=(3,4,5))
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor datatype: {tensor.dtype}")
print(f"Tensor device: {tensor.device}")

Tensor shape: torch.Size([3, 4, 5])
Tensor datatype: torch.float32
Tensor device: cpu


### Changing tensor attributes
To change dtype or device for a tensor, we can use the `.to()` method

In [31]:
# Change tensor from float32 to float16
float32_tensor = torch.rand(size=(3,4), dtype=torch.float32)
print(float32_tensor.dtype)
float16_tensor = float32_tensor.to(dtype=torch.float16)
print(float16_tensor.dtype)

torch.float32
torch.float16


### Tensor operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Matrix multiplication (dot product)
* Division


In [32]:
# Addition
tensor = torch.tensor([4,5,6])
tensor + 10

tensor([14, 15, 16])

In [33]:
tensor1 = torch.tensor([6,7,8])
tensor + tensor1

tensor([10, 12, 14])

In [34]:
# Scalar multiplication
tensor * 10

tensor([40, 50, 60])

In [36]:
# Subtraction
tensor - 20

tensor([-16, -15, -14])

In [37]:
# Division
tensor / 10

tensor([0.4000, 0.5000, 0.6000])

In [38]:
# Element wise mulitplication
tensor1 = torch.tensor([2,3,4])
tensor2 = torch.tensor([6,7,8])
tensor1 * tensor2

tensor([12, 21, 32])

In [39]:
# Matrix multiplication
torch.matmul(tensor1, tensor2)

tensor(65)

### A common issue in deep learning is shape errors:
Having tensors of incorrect size when trying to do matrix multiplication results in an error

There are two main rules that should be follwed when performing matrix operations:
1. The **inner dimensions** must match:
* `(3,2) @ (2,3)` will work, but
* `(3,2) @ (3,2)` won't work
2. The resulting matrix must have the shape of the **outer dimensions**:
* `(3,2) @ (2,3)` will have shape (3,3)
* `(4,5) @ (5,4)` will have shape (5,5)

In [47]:
# Shapes for matrix multiplication
tensor1 = torch.tensor([[1,2], [3,4], [5,6]])
tensor2 = torch.tensor([[7,8,9], [10,11,12]])
torch.matmul(tensor1, tensor2)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### To fix shape mismatch issue when multiplying tensors, we can use transpose:

**Transpose** switched the rows and columns of a tensor

It lets us turn a tensor of shape (a,b) into tensor of shape (b,a)


In [48]:
# Example:
tensor1 = torch.tensor([[1,2], [3,4], [5,6]])
tensor2 = torch.tensor([[7,8], [10,11], [12,13]])
torch.mm(tensor1, tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
# Since the last case resulted in an error, we can now transpose one of the tensors to be able to use matrix multiplication on them:
tensor2 = tensor2.T
torch.mm(tensor1, tensor2)

tensor([[ 23,  32,  38],
        [ 53,  74,  88],
        [ 83, 116, 138]])

### Tensor aggregation
There are other operation we may do on tensors that give us some information about their contents:
* min
* max
* mean
* sum

In [52]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# .min() - returns the smallest element of the tensor
x.min()

tensor(0)

In [57]:
# .min() - returns the largest element of the tensor
x.max()

tensor(9)

In [63]:
# .sum() returns the sum of the elements of the tensor
x.sum()

tensor(45)

In [65]:
# .mean() returns the mean of the elements of the tensor
# !!! Only works with complex or float types
x = x.to(dtype=torch.float32)
x.mean()

tensor(4.5000)

In [67]:
# To find the position of the min and max values, we can use torch.argmin() and torch.argmax():
torch.argmin(x)

tensor(0)

In [69]:
torch.argmax(x)

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping is the operation of reshaping a tensor into a different shape
* View returns a view of an input tensor of certain shape, but keeps the same memory as original tensor
* Stacking is the operation of combining multiple tensors
  * vstack - vertical stack, stacks tensors vertically
  * hstack - horizontal stack, stacks tensors side by side
* Squeezing is the operation of removing all `1` dimensions from a tensor
* Unsqueezing is the operation of adding a `1` dimension to a tensor
* Permuting returns a view of the input with certain dimensions swapped

In [70]:
# Reshape
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Reshape
# Add an extra dimension (the reshape shape must be compatible with the dimension of the original)
# For the reshape to work, the multiple of the new dimensions must be the same as the multiple of the previous dimensions
x.reshape(shape=(1,9))


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:
x.reshape(shape=(9,1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [77]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# Change the view
