In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Introduction to Tensors
### Scalar

In [3]:
# Scalar
# Usually the variable name is lowercase in code
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get number of tensor dimensions
scalar.ndim

0

In [5]:
# Get python equivalent of the tensor
scalar.item()

7

In [6]:
# Vector
# Usually the variable name is lowercase in code
vector = torch.tensor([[1],[2],[3]])
vector

tensor([[1],
        [2],
        [3]])

In [7]:
# Get shape of the tensor
vector.shape

torch.Size([3, 1])

In [8]:
# MATRIX
# Usually the variable name is uppercase in code
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
# Usually the variable name is uppercase in code
TENSOR = torch.tensor([[[1,2,3]]])

### Random Tensors

Random tensors are important, because many neural networks learn by starting with tensors with random numbers, and then adjusting them to better represent the data.

One example of such a workflow would be:
1. Start with random numbers
2. Look at the data
3. Update the random numbers
4. Repeat steps 2-3

In [12]:
# Create a random tensor of size/shape (a, b)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5908, 0.5118, 0.0525, 0.9659],
        [0.2637, 0.3918, 0.9976, 0.9872],
        [0.3944, 0.7442, 0.7250, 0.0743]])

In [13]:
# Create a random tensor with a shape similar to an image tensor
random_image_shape_tensor = torch.rand(size = (224,223,3))
random_image_shape_tensor.shape, random_image_shape_tensor.ndim

(torch.Size([224, 223, 3]), 3)

### A tensor of zeros and ones

In [14]:
# Create a tensor of zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
# Create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors shaped like other tensors

In [17]:
# Use torch.arange() - torch.range() is deprecated!
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
range_zeroes = torch.zeros_like(input=range)
range_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Another example:
rand_vector = torch.rand((2,4))
rand_vector_zeroes = torch.zeros_like(input=rand_vector)
rand_vector, rand_vector_zeroes

(tensor([[0.0374, 0.6152, 0.3592, 0.3820],
         [0.2150, 0.4859, 0.6096, 0.7264]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### Tensors datatypes

Note: Tensor datatypes is one of the three main issues that are often enountered in PyTorch and Deep Learning:
1. Wrong datatype of a tensor
2. Wrong shape of a tensor
3. A tensor is on a wrong device

In [24]:
# Float 32 tensor
# Parameters dtype, device and requires_grad are the 3 most important parameters when creating tensor

# dtype is the datatype of the tensor (e.g float32, float 16 etc.)

# device is the hardware which is used to creat the tensor - it is set to cpu by default but can be changed
# One error we may get is when trying to do operations on tensors that are on different devices and are therefore incompatible

# required_grad is for when we want to track the gradience of a tensor when it through certain calculations

float_32_tensor = torch.tensor([1.5,2.5,4.5], dtype=None, device=None, requires_grad=None)
float_32_tensor

tensor([1.5000, 2.5000, 4.5000])

In [25]:
# Even thought the dtype is specified as none, it will still default to float32
float_32_tensor.dtype

torch.float32